apiVersion: v1
kind: Service
metadata:
  name: svc-webapp
  labels:
    app: svc-webapp-label
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: template-webapp-label